services:
  backend:
    build: ./backend
    container_name: potato-health-backend
    ports:
      - "22555:22555"
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
    environment:
      - OPENBLAS_NUM_THREADS=1
    restart: always

  frontend:
    build: ./frontend
    container_name: potato-health-frontend
    ports:
      - "22444:22444"
    depends_on:
      - backend
    restart: always
